apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-psql
  labels:
    app: psql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
